[workspace]
members = ["libpenguin", "penguin-cli"]
default-members = ["penguin-cli"]
resolver = "3"

[workspace.dependencies]
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
thiserror = "2.0.18"
