[package]
name = "penguin-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
thiserror.workspace = true
clap = { version = "4.5.58", features = ["derive"] }
csv = "1.4.0"
libpenguin = { path = "../libpenguin/" }
